### PR TITLE
Assignment

### PR DESCRIPTION
**Pull request by devangi-hub**
TITLE: UofT-DSI | Shell - Assignment 1

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
I have updated the assignment answers
## What did you learn from the changes you have made?
I have learn the basic Git & shell commands
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
This was the basic straightforward solution
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
I have not face any major challenges in completing this assignment.
## How were these changes tested?
I have locally tested, running the script.
## Checklist
- [ X ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by monzchan** [comment]
@devangi-hub Please make sure you have completed part 2 of the assignment (you may see it in the assignment_instruction file)

**Comment by devangi-hub** [comment]
@monzchan  Can you please let me know if anything is pending.

**Comment by monzchan** [comment]
Great job! It's perfect!

**Comment by devangi-hub** [comment]
closing this

**Pull request merged**
